### Spring ###
spring:

  ### Application ###
  application:
    name: person-service

  ### Config ###
  config:
    import: "configserver:"

  ### Cloud config ###
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        max-interval: 5000
      uri: http://localhost:9999
