/* Person */
create table if not exists person
(
    /* Generic data */
    id          bigint generated by default as identity not null
        constraint person_pk primary key,
    version     bigint default 0                        not null,

    /* Personal data */
    last_name   varchar(255)                            not null,
    first_name  varchar(255)                            not null,
    middle_name varchar(255)                            not null,
    birth_day   date                                    not null
);
